name: project
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python
  - anaconda
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - -e .
      - -r file:requirements.txt
      - -r file:tests/requirements.txt